// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function CleanTaxID(arg1:string):Promise<string>;

export function EmailPreset(arg1:string):Promise<backend.PresetResult>;

export function FindInvoiceTemplate():Promise<string>;

export function GenerateInvoice(arg1:Array<backend.Invoice>,arg2:backend.FixedContent,arg3:string,arg4:string):Promise<backend.InvoiceResult>;

export function Greet(arg1:string):Promise<string>;

export function ImportInvoiceDetail(arg1:string):Promise<backend.ImportResult>;

export function ListSheets(arg1:string):Promise<Array<string>>;

export function LoadEmailConfig():Promise<backend.EmailConfig>;

export function LoadFixedConfig():Promise<backend.FixedContent>;

export function ReadSheet(arg1:string,arg2:string):Promise<Array<any>>;

export function RunImgConvert(arg1:string,arg2:string,arg3:number):Promise<backend.ImgConvertResult>;

export function RunMatch(arg1:string,arg2:string,arg3:string,arg4:string,arg5:Array<any>,arg6:string,arg7:string,arg8:boolean):Promise<backend.MatchResult>;

export function SaveEmailConfig(arg1:backend.EmailConfig):Promise<void>;

export function SaveFixedConfig(arg1:backend.FixedContent):Promise<void>;

export function SelectDir():Promise<string>;

export function SelectFile():Promise<string>;

export function SelectSavePath(arg1:string):Promise<string>;

export function SendEmail(arg1:backend.EmailConfig,arg2:string,arg3:string,arg4:string,arg5:Array<string>):Promise<backend.EmailResult>;
