// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GenerateInvoice(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GenerateInvoice'](arg1, arg2, arg3, arg4);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ImportInvoiceDetail(arg1) {
  return window['go']['main']['App']['ImportInvoiceDetail'](arg1);
}

export function ListSheets(arg1) {
  return window['go']['main']['App']['ListSheets'](arg1);
}

export function ReadSheet(arg1, arg2) {
  return window['go']['main']['App']['ReadSheet'](arg1, arg2);
}

export function RunMatch(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['main']['App']['RunMatch'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function SelectFile() {
  return window['go']['main']['App']['SelectFile']();
}

export function SelectSavePath(arg1) {
  return window['go']['main']['App']['SelectSavePath'](arg1);
}
