// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function GenerateInvoice(arg1:Array<backend.Invoice>,arg2:backend.FixedContent,arg3:string,arg4:string):Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function ListSheets(arg1:string):Promise<Array<string>>;

export function ReadSheet(arg1:string,arg2:string):Promise<Array<any>>;

export function RunMatch(arg1:string,arg2:string,arg3:string,arg4:string,arg5:Array<any>,arg6:string,arg7:string,arg8:boolean):Promise<backend.MatchResult>;

export function SelectFile():Promise<string>;

export function SelectSavePath(arg1:string):Promise<string>;
