// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CleanTaxID(arg1) {
  return window['go']['main']['App']['CleanTaxID'](arg1);
}

export function DownloadBackgroundImage(arg1) {
  return window['go']['main']['App']['DownloadBackgroundImage'](arg1);
}

export function EmailPreset(arg1) {
  return window['go']['main']['App']['EmailPreset'](arg1);
}

export function FindInvoiceTemplate() {
  return window['go']['main']['App']['FindInvoiceTemplate']();
}

export function GenerateInvoice(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GenerateInvoice'](arg1, arg2, arg3, arg4);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ImportInvoiceDetail(arg1) {
  return window['go']['main']['App']['ImportInvoiceDetail'](arg1);
}

export function ListSheets(arg1) {
  return window['go']['main']['App']['ListSheets'](arg1);
}

export function LoadEmailConfig() {
  return window['go']['main']['App']['LoadEmailConfig']();
}

export function LoadFixedConfig() {
  return window['go']['main']['App']['LoadFixedConfig']();
}

export function ReadSheet(arg1, arg2) {
  return window['go']['main']['App']['ReadSheet'](arg1, arg2);
}

export function RunImgConvert(arg1, arg2, arg3) {
  return window['go']['main']['App']['RunImgConvert'](arg1, arg2, arg3);
}

export function RunMatch(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['main']['App']['RunMatch'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function SaveEmailConfig(arg1) {
  return window['go']['main']['App']['SaveEmailConfig'](arg1);
}

export function SaveFixedConfig(arg1) {
  return window['go']['main']['App']['SaveFixedConfig'](arg1);
}

export function SelectDir() {
  return window['go']['main']['App']['SelectDir']();
}

export function SelectFile() {
  return window['go']['main']['App']['SelectFile']();
}

export function SelectSavePath(arg1) {
  return window['go']['main']['App']['SelectSavePath'](arg1);
}

export function SendEmail(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SendEmail'](arg1, arg2, arg3, arg4, arg5);
}
